### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by genox** [RSC-Labs/medusa-products-bought-together#1]
Hi,

Tried to install according to the readme, got this error:

```
yarn add medusa-products-bought-together
➤ YN0027: medusa-products-bought-together@unknown can't be resolved to a satisfying range
➤ YN0035: Package not found
➤ YN0035:   Response Code: 404 (Not Found)
➤ YN0035:   Request Method: GET
➤ YN0035:   Request URL: https://registry.yarnpkg.com/medusa-products-bought-together

```

**Comment by radoslaw-sz** [comment]
hi @genox ,
You are right, sorry for confusion. I have updated README with proper name - it shall be `@rsc-labs/medusa-products-bought-together`. Please kindly check it it works.

**Comment by radoslaw-sz** [comment]
hi @genox  I am closing this issue due to no response - in case of problem, do not hesitate to open again., thanks!
