### ISSUE TITLE
productsBoughtTogetherOrderHandler isnt being called as subscriber 

### ISSUE THREAD

**Issue by melonaster3** [RSC-Labs/medusa-products-bought-together#2]
Installed the package, added it as a plugin, but when I place an order using the store front, the order.placed subsciber isnt updated. 

```
info:    Processing order.placed which has 3 subscribers
```

Hence service isnt being called, and the data isnt being updated

**Comment by radoslaw-sz** [comment]
hi @melonaster3  - thanks for raising this issue, it is strange because it is basic functionality. Let me take a look at this and I will back to you.

**Comment by radoslaw-sz** [comment]
hi @melonaster3
I just checked and locally on my side it is working (I just put random string to see if order.placed has been execute for subscriber)
![image](https://github.com/RSC-Labs/medusa-products-bought-together/assets/54472480/5c996f42-f246-49fc-9870-87c1682009c1)

Could you please explain why you think it is not called? Did you check DB? Did you run migrations before?

**Comment by melonaster3** [comment]
Came back after the weekend, didnt change a single line of code and now it magically works. Could be build issue or vscode or DB issue. My bad, will close the issue.
