### ISSUE TITLE
Dependency error on installation

### ISSUE THREAD

**Issue by SubhrajitDG** [RSC-Labs/medusa-products-bought-together#3]
Please bump the medusajs version

my Node version is - v21.5.0.
"@medusajs/medusa": "^1.20.6",

**Comment by radoslaw-sz** [comment]
hi @SubhrajitDG  - update landed in version 0.1.5. Please kindly check.

**Comment by SubhrajitDG** [comment]
hi @radoslaw-sz - Issue still persists. Should be ^1.20.6

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: medusa-starter-default@0.0.1
npm ERR! Found: @medusajs/medusa@1.20.7
npm ERR! node_modules/@medusajs/medusa
npm ERR!   @medusajs/medusa@"^1.20.6" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @medusajs/medusa@"1.19.0" from @rsc-labs/medusa-products-bought-together@0.1.5
npm ERR! node_modules/@rsc-labs/medusa-products-bought-together
npm ERR!   @rsc-labs/medusa-products-bought-together@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by radoslaw-sz** [comment]
.... I changed dependencies but not the peer dependencies 🤦 
New version has been released - 0.1.6.

**Comment by radoslaw-sz** [comment]
hi @SubhrajitDG  - kindly check please

**Comment by SubhrajitDG** [comment]
thanks, it installed correctly
